In [1]:
import pandas as pd

In [ ]:
binary_tree = pd.read_csv('format-results/binary-tree.csv')
binary_tree = binary_tree[binary_tree['ModelName'].isin(['Qwen2.5-32B-Instruct', 'Qwen2.5-7B-Instruct'])].replace('Qwen2.5-32B-Instruct', 'QwQ-32B')
qwen_7      = binary_tree[binary_tree['ModelName'] == 'Qwen2.5-7B-Instruct'].groupby('ExampleType')['Accuracy'].mean()
qwq         = binary_tree[binary_tree['ModelName'] == 'QwQ-32B'].groupby('ExampleType')['Accuracy'].mean()
binary_tree_cot = pd.read_excel('dataview/binary-tree-CoT.xlsx', sheet_name='ModelName')
qwen_7, qwq

(ExampleType
 FewShot     35.738472
 OneShot     31.494167
 ZeroShot    33.108472
 Name: Accuracy, dtype: float64,
 ExampleType
 ZeroShot    42.907917
 Name: Accuracy, dtype: float64)

In [3]:
binary_tree_cot

             ModelName       mean        std  count
0              QwQ-32B  42.007361  32.648895     72
1  Qwen2.5-7B-Instruct  33.062917  30.912592     72

In [4]:
multiple_tree = pd.read_csv('format-results/multiple-tree.csv')
multiple_tree = multiple_tree[multiple_tree['ModelName'].isin(['Qwen2.5-32B-Instruct', 'Qwen2.5-7B-Instruct'])].replace('Qwen2.5-32B-Instruct', 'QwQ-32B')
qwen_7      = multiple_tree[multiple_tree['ModelName'] == 'Qwen2.5-7B-Instruct'].groupby('ExampleType')['Accuracy'].mean()
qwq         = multiple_tree[multiple_tree['ModelName'] == 'QwQ-32B'].groupby('ExampleType')['Accuracy'].mean()
multiple_tree_cot = pd.read_excel('dataview/multiple-tree-CoT.xlsx', sheet_name='ModelName')
qwen_7, qwq

(ExampleType
 FewShot     57.437593
 OneShot     55.431852
 ZeroShot    54.861111
 Name: Accuracy, dtype: float64,
 ExampleType
 ZeroShot    74.116481
 Name: Accuracy, dtype: float64)

In [5]:
multiple_tree_cot

             ModelName       mean        std  count
0              QwQ-32B  42.885556  24.169868     54
1  Qwen2.5-7B-Instruct  58.191296  23.188727     54

# Fine Granularity

In [12]:
binary_ret = dict()
binary_tree = pd.read_csv('format-results/binary-tree.csv')
binary_tree = binary_tree[binary_tree['ExampleType'] == 'ZeroShot']
binary_tree = binary_tree[binary_tree['ModelName'].isin(['Qwen2.5-32B-Instruct', 'Qwen2.5-7B-Instruct'])].replace('Qwen2.5-32B-Instruct', 'QwQ-32B')
binary_ret['Qwen-7B'] = binary_tree[binary_tree['ModelName'] == 'Qwen2.5-7B-Instruct'].groupby('SubTask')['Accuracy'].mean()
binary_ret['QwQ-32B'] = binary_tree[binary_tree['ModelName'] == 'QwQ-32B'].groupby('SubTask')['Accuracy'].mean()

binary_tree_cot = pd.read_csv('./format-results/binary-tree-CoT.csv')
binary_ret['Qwen-7B-CoT'] = binary_tree_cot[binary_tree_cot['ModelName'] == 'Qwen2.5-7B-Instruct'].groupby('SubTask')['Accuracy'].mean()
binary_ret['QwQ-32B-CoT'] = binary_tree_cot[binary_tree_cot['ModelName'] == 'QwQ-32B'].groupby('SubTask')['Accuracy'].mean()
pd.DataFrame(binary_ret)

                                Qwen-7B    QwQ-32B  Qwen-7B-CoT  QwQ-32B-CoT
SubTask
balance                       41.551667  45.370833    48.340000    50.269167
infix_traversal               29.400000  46.951667    27.739167    30.865000
mirror_tree                    7.638333   7.177500     8.642500     2.855000
postfix_traversal             30.323333  29.167500    29.359167    44.134167
prefix_traversal              40.972500  65.200000    38.386667    42.593333
traversal_order_verification  48.765000  63.580000    45.910000    81.327500

In [13]:
multiple_ret = dict()
multiple_tree = pd.read_csv('format-results/multiple-tree.csv')
multiple_tree = multiple_tree[multiple_tree['ExampleType'] == 'ZeroShot']
multiple_tree = multiple_tree[multiple_tree['ModelName'].isin(['Qwen2.5-32B-Instruct', 'Qwen2.5-7B-Instruct'])].replace('Qwen2.5-32B-Instruct', 'QwQ-32B')
multiple_ret['Qwen-7B'] = multiple_tree[multiple_tree['ModelName'] == 'Qwen2.5-7B-Instruct'].groupby('SubTask')['Accuracy'].mean()
multiple_ret['QwQ-32B'] = multiple_tree[multiple_tree['ModelName'] == 'QwQ-32B'].groupby('SubTask')['Accuracy'].mean()

multiple_tree_cot = pd.read_csv('./format-results/multiple-tree-CoT.csv')
multiple_ret['Qwen-7B-CoT'] = multiple_tree_cot[multiple_tree_cot['ModelName'] == 'Qwen2.5-7B-Instruct'].groupby('SubTask')['Accuracy'].mean()
multiple_ret['QwQ-32B-CoT'] = multiple_tree_cot[multiple_tree_cot['ModelName'] == 'QwQ-32B'].groupby('SubTask')['Accuracy'].mean()
pd.DataFrame(multiple_ret)

                   Qwen-7B     QwQ-32B  Qwen-7B-CoT  QwQ-32B-CoT
SubTask
add_node         57.281667   86.658333    36.300000     3.788333
all_ancestor     47.770000   93.053333    55.303333    63.195000
all_children     75.800000   90.508333    76.326667    59.533333
common_ancestor  56.481667   86.638333    72.601667    29.210000
isomorphic       40.865000   49.600000    63.405000    56.001667
leaf             53.978333   83.691667    73.023333    82.283333
node_depth       20.915000   12.753333    16.856667    30.365000
remove_node      50.253333   64.145000    44.486667    22.241667
root             90.405000  100.000000    85.418333    39.351667