In [1]:
import pandas as pd

In [2]:
binary_tree     = pd.read_excel('dataview/binary-tree.xlsx', sheet_name='ModelName')
binary_tree     = binary_tree[binary_tree['ModelName'].isin(['Qwen2.5-32B-Instruct', 'Qwen2.5-7B-Instruct'])].replace('Qwen2.5-32B-Instruct', 'QwQ-32B')
binary_tree_cot = pd.read_excel('dataview/binary-tree-CoT.xlsx', sheet_name='ModelName')

binary_tree

              ModelName       mean        std  count
10              QwQ-32B  42.907917  35.197389     72
13  Qwen2.5-7B-Instruct  33.108472  33.019017     72

In [3]:
binary_tree_cot

             ModelName       mean        std  count
0              QwQ-32B  42.007361  32.648895     72
1  Qwen2.5-7B-Instruct  33.062917  30.912592     72

In [4]:
multiple_tree     = pd.read_excel('dataview/multiple-tree.xlsx', sheet_name='ModelName')
multiple_tree     = multiple_tree[multiple_tree['ModelName'].isin(['Qwen2.5-32B-Instruct', 'Qwen2.5-7B-Instruct'])].replace('Qwen2.5-32B-Instruct', 'QwQ-32B')
multiple_tree_cot = pd.read_excel('dataview/multiple-tree-CoT.xlsx', sheet_name='ModelName')
multiple_tree

              ModelName       mean        std  count
11              QwQ-32B  74.116481  27.164828     54
14  Qwen2.5-7B-Instruct  54.861111  21.569336     54

In [5]:
multiple_tree_cot

             ModelName       mean        std  count
0              QwQ-32B  42.885556  24.169868     54
1  Qwen2.5-7B-Instruct  58.191296  23.188727     54